import React, { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { useGenerateTrip, useSaveTrip } from "@/lib/api-client";
import { PlannerForm, PlannerFormValues } from "@/components/planner-form";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Skeleton } from "@/components/ui/skeleton";
import { Map, Calendar, Hotel, Train, Backpack, DollarSign, Bookmark, AlertCircle, Sunrise, Sunset, Cloud, Star } from "lucide-react";
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend } from "recharts";

export default function Plan() {
  const [location, setLocation] = useLocation();
  const { toast } = useToast();
  
  const searchParams = new URLSearchParams(window.location.search);
  const initialData: Partial<PlannerFormValues> = {
    destination: searchParams.get("destination") || "",
    days: searchParams.get("days") ? Number(searchParams.get("days")) : undefined,
    budget: searchParams.get("budget") ? Number(searchParams.get("budget")) : undefined,
    travelStyle: (searchParams.get("travelStyle") as any) || undefined,
  };

  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const generateTrip = useGenerateTrip();
  const saveTrip = useSaveTrip();

  const handleGenerate = (data: PlannerFormValues) => {
    // Update URL to match current form state without full reload
    const params = new URLSearchParams();
    Object.entries(data).forEach(([key, value]) => params.append(key, String(value)));
    window.history.replaceState({}, "", `/plan?${params.toString()}`);

    generateTrip.mutate({
      data: {
        destination: data.destination,
        days: data.days,
        budget: data.budget,
        travelStyle: data.travelStyle as any,
        currency: "USD",
        groupSize: 1
      }
    });
  };

  // Auto-generate if we came from the home page with full params
  useEffect(() => {
    if (
      !hasAutoGenerated && 
      initialData.destination && 
      initialData.days && 
      initialData.budget && 
      initialData.travelStyle &&
      !generateTrip.data &&
      !generateTrip.isPending
    ) {
      setHasAutoGenerated(true);
      handleGenerate(initialData as PlannerFormValues);
    }
  }, [initialData, hasAutoGenerated, generateTrip.data, generateTrip.isPending]);

  const handleSave = () => {
    if (!generateTrip.data) return;
    
    saveTrip.mutate({
      data: {
        destination: initialData.destination || "Unknown",
        days: initialData.days || 5,
        budget: initialData.budget || 1500,
        travelStyle: initialData.travelStyle || "comfort",
        currency: "USD",
        plan: generateTrip.data
      }
    }, {
      onSuccess: (savedTrip) => {
        toast({
          title: "Trip Saved!",
          description: "You can view it anytime in your Saved Trips.",
        });
        setLocation(`/trips/${savedTrip.id}`);
      },
      onError: () => {
        toast({
          variant: "destructive",
          title: "Failed to save trip",
          description: "An error occurred while saving your trip. Please try again.",
        });
      }
    });
  };

  const tripPlan = generateTrip.data;
  const isGenerating = generateTrip.isPending;

  // Chart colors derived from theme
  const CHART_COLORS = ['hsl(var(--chart-1))', 'hsl(var(--chart-2))', 'hsl(var(--chart-3))', 'hsl(var(--chart-4))', 'hsl(var(--chart-5))'];

  return (
    <div className="container mx-auto px-4 py-8 max-w-6xl">
      <div className="mb-8">
        <h1 className="text-3xl font-serif font-bold mb-6">AI Trip Planner</h1>
        <div className="bg-card border rounded-xl p-4 md:p-6 shadow-sm">
          <PlannerForm 
            defaultValues={initialData} 
            onSubmit={handleGenerate} 
            isLoading={isGenerating} 
            variant="horizontal"
          />
        </div>
      </div>

      {isGenerating && (
        <div className="space-y-8 animate-pulse">
          <div className="text-center py-12">
            <h2 className="text-2xl font-serif font-medium text-muted-foreground animate-pulse mb-4">
              Our AI is exploring {initialData.destination || "the world"} for you...
            </h2>
            <p className="text-muted-foreground">Analyzing optimal routes, checking accommodations, and balancing your budget.</p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-6">
            <div className="md:col-span-2 space-y-6">
              <Skeleton className="h-48 w-full rounded-xl" />
              <Skeleton className="h-96 w-full rounded-xl" />
            </div>
            <div className="space-y-6">
              <Skeleton className="h-64 w-full rounded-xl" />
              <Skeleton className="h-64 w-full rounded-xl" />
            </div>
          </div>
        </div>
      )}

      {generateTrip.isError && (
        <div className="bg-destructive/10 text-destructive p-6 rounded-xl border border-destructive/20 flex flex-col items-center text-center">
          <AlertCircle className="w-12 h-12 mb-4 opacity-80" />
          <h3 className="text-xl font-bold mb-2">Generation Failed</h3>
          <p className="max-w-md">We couldn't generate your trip plan right now. Our AI might be taking a quick nap. Please try again.</p>
          <Button variant="outline" className="mt-6" onClick={() => handleGenerate(initialData as PlannerFormValues)}>
            Retry Generation
          </Button>
        </div>
      )}

      {tripPlan && !isGenerating && (
        <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
          {/* Header Actions */}
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-primary/5 p-6 rounded-xl border">
            <div>
              <h2 className="text-2xl font-serif font-bold text-primary">Your customized journey awaits.</h2>
              <p className="text-muted-foreground mt-1">{tripPlan.summary}</p>
            </div>
            <Button onClick={handleSave} size="lg" disabled={saveTrip.isPending} className="shrink-0 shadow-lg hover-elevate">
              <Bookmark className="w-4 h-4 mr-2" />
              {saveTrip.isPending ? "Saving..." : "Save Trip"}
            </Button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="md:col-span-2 space-y-6">
              {/* Itinerary */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 font-serif text-2xl">
                    <Calendar className="w-5 h-5 text-primary" /> Daily Itinerary
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-8">
                    {tripPlan.itinerary.map((day, idx) => (
                      <div key={idx} className="relative pl-6 before:absolute before:left-0 before:top-2 before:bottom-0 before:w-px before:bg-border last:before:hidden">
                        <div className="absolute left-[-4px] top-2 w-2 h-2 rounded-full bg-primary ring-4 ring-background"></div>
                        <h3 className="font-bold text-lg mb-4">Day {day.day}: {day.title}</h3>
                        
                        <div className="space-y-4">
                          {day.activities.map((activity, aIdx) => (
                            <div key={aIdx} className="bg-muted/40 rounded-lg p-4 border border-border/50">
                              <div className="flex justify-between items-start mb-2">
                                <span className="font-semibold">{activity.name}</span>
                                <span className="text-sm text-primary font-medium">{activity.time}</span>
                              </div>
                              <p className="text-sm text-muted-foreground mb-2">{activity.description}</p>
                              {activity.estimatedCost && (
                                <div className="text-xs font-medium bg-background border px-2 py-1 rounded w-fit text-muted-foreground">
                                  Est. Cost: ${activity.estimatedCost}
                                </div>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </div>

            <div className="space-y-6">
              {/* Weather & Info */}
              {(tripPlan.bestTimeToVisit || tripPlan.weather) && (
                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg font-serif">Quick Intel</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {tripPlan.bestTimeToVisit && (
                      <div className="flex items-start gap-3">
                        <Sunrise className="w-5 h-5 text-muted-foreground shrink-0 mt-0.5" />
                        <div>
                          <p className="font-medium text-sm">Best Time to Visit</p>
                          <p className="text-sm text-muted-foreground">{tripPlan.bestTimeToVisit}</p>
                        </div>
                      </div>
                    )}
                    {tripPlan.weather && (
                      <div className="flex items-start gap-3">
                        <Cloud className="w-5 h-5 text-muted-foreground shrink-0 mt-0.5" />
                        <div>
                          <p className="font-medium text-sm">Typical Weather</p>
                          <p className="text-sm text-muted-foreground">{tripPlan.weather}</p>
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}

              {/* Budget Breakdown */}
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg font-serif flex items-center gap-2">
                    <DollarSign className="w-5 h-5 text-primary" /> Budget Breakdown
                  </CardTitle>
                  <CardDescription>
                    Total Est: ${tripPlan.budgetBreakdown.total} {tripPlan.budgetBreakdown.currency}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="h-48 mb-4">
                    <ResponsiveContainer width="100%" height="100%">
                      <PieChart>
                        <Pie
                          data={[
                            { name: 'Accommodation', value: tripPlan.budgetBreakdown.accommodation },
                            { name: 'Transport', value: tripPlan.budgetBreakdown.transport },
                            { name: 'Food', value: tripPlan.budgetBreakdown.food },
                            { name: 'Activities', value: tripPlan.budgetBreakdown.activities },
                            { name: 'Misc', value: tripPlan.budgetBreakdown.miscellaneous },
                          ]}
                          cx="50%"
                          cy="50%"
                          innerRadius={50}
                          outerRadius={70}
                          paddingAngle={2}
                          dataKey="value"
                        >
                          {CHART_COLORS.map((color, index) => (
                            <Cell key={`cell-${index}`} fill={color} />
                          ))}
                        </Pie>
                        <Tooltip formatter={(value) => `$${value}`} />
                      </PieChart>
                    </ResponsiveContainer>
                  </div>
                  
                  <div className="space-y-2 text-sm">
                    <div className="flex justify-between"><span className="flex items-center gap-2"><div className="w-3 h-3 rounded-full" style={{backgroundColor: CHART_COLORS[0]}}></div>Accommodation</span> <span>${tripPlan.budgetBreakdown.accommodation}</span></div>
                    <div className="flex justify-between"><span className="flex items-center gap-2"><div className="w-3 h-3 rounded-full" style={{backgroundColor: CHART_COLORS[1]}}></div>Transport</span> <span>${tripPlan.budgetBreakdown.transport}</span></div>
                    <div className="flex justify-between"><span className="flex items-center gap-2"><div className="w-3 h-3 rounded-full" style={{backgroundColor: CHART_COLORS[2]}}></div>Food</span> <span>${tripPlan.budgetBreakdown.food}</span></div>
                    <div className="flex justify-between"><span className="flex items-center gap-2"><div className="w-3 h-3 rounded-full" style={{backgroundColor: CHART_COLORS[3]}}></div>Activities</span> <span>${tripPlan.budgetBreakdown.activities}</span></div>
                  </div>
                </CardContent>
              </Card>

              {/* Tabs for extra details */}
              <Tabs defaultValue="hotels" className="w-full">
                <TabsList className="grid w-full grid-cols-3">
                  <TabsTrigger value="hotels"><Hotel className="w-4 h-4 mr-2 hidden sm:block" /> Hotels</TabsTrigger>
                  <TabsTrigger value="transport"><Train className="w-4 h-4 mr-2 hidden sm:block" /> Travel</TabsTrigger>
                  <TabsTrigger value="packing"><Backpack className="w-4 h-4 mr-2 hidden sm:block" /> Pack</TabsTrigger>
                </TabsList>
                
                <TabsContent value="hotels" className="space-y-4 mt-4">
                  {tripPlan.hotels.map((hotel, idx) => (
                    <div key={idx} className="bg-card border rounded-lg p-4">
                      <div className="flex justify-between items-start">
                        <h4 className="font-bold font-serif">{hotel.name}</h4>
                        <span className="text-sm font-medium bg-primary/10 text-primary px-2 py-0.5 rounded">${hotel.pricePerNight}/n</span>
                      </div>
                      <div className="flex items-center gap-1 text-yellow-500 my-1">
                        {Array.from({ length: hotel.stars }).map((_, i) => <Star key={i} className="w-3 h-3 fill-current" />)}
                      </div>
                      <p className="text-sm text-muted-foreground mt-2">{hotel.description}</p>
                    </div>
                  ))}
                </TabsContent>
                
                <TabsContent value="transport" className="space-y-4 mt-4">
                  {tripPlan.transport.map((t, idx) => (
                    <div key={idx} className="bg-card border rounded-lg p-4">
                      <h4 className="font-bold capitalize">{t.type}</h4>
                      <p className="text-sm text-muted-foreground mt-1">{t.description}</p>
                      <div className="flex justify-between items-center mt-3 pt-3 border-t">
                        <span className="text-sm font-medium">Est. Cost</span>
                        <span className="text-sm font-medium">${t.estimatedCost}</span>
                      </div>
                    </div>
                  ))}
                </TabsContent>
                
                <TabsContent value="packing" className="space-y-4 mt-4">
                  {tripPlan.packingList.map((category, idx) => (
                    <div key={idx}>
                      <h4 className="font-bold text-sm text-muted-foreground uppercase tracking-wider mb-2">{category.category}</h4>
                      <div className="flex flex-wrap gap-2">
                        {category.items.map((item, i) => (
                          <span key={i} className="bg-muted px-2 py-1 rounded text-xs border">{item}</span>
                        ))}
                      </div>
                    </div>
                  ))}
                </TabsContent>
              </Tabs>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
